---
title: "EY_test1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

#Load Package
```{r}
library(readxl)
library(tidyverse)
library(lavaan)
library(psych)
```

#loading Dataset
```{r}
P1 <- read_excel("NIH P1 Emotion Understanding SDS300.xlsx")
```

#Clean Data
```{r}
names(P1)<-str_replace_all(names(P1), c(" " = "" )) 
P1<- P1 %>%
  mutate(IGroup = as.factor(IGroup))
```

```{r}
library("Hmisc")

corP1 <- P1 %>%
  select(-ETHNICITY,-child_ID, -Gender, -Intervention, -IGroup)


mcor<-round(cor(corP1),2)

corP1 <- rcorr(as.matrix(corP1))
```

```{r}

cor.plot(corP1$r)
```

Model 
```{r}
#cross-lagged full model 
P1 <- P1 %>%
  mutate(Intervention = as.factor(Intervention))

model_1 <- "PLS4compraw3 ~ PLS4compraw1 + Intervention + EOWPVTraw1 + EMOtotal1
          EOWPVTraw3 ~ EOWPVTraw1 + Intervention + PLS4compraw1 + EMOtotal1
          EMOtotal3 ~ EMOtotal1 + Intervention + PLS4compraw1 + EOWPVTraw1"
fit_1 = sem(model_1, data = P1)
summary(fit_1, standardized = TRUE, fit.measures = TRUE, rsquare = TRUE)
```

```{r}
library(semPlot)
semPaths(fit_1,rotation=2)
```
```{r}
#only look at emotion 
model_2 <- "EMOsit3 ~ EMOsit1 + EMOdesire1 + Intervention
          EMOdesire3 ~ EMOsit1 + EMOdesire1 + Intervention"
fit_2 = sem(model_2, data = P1)
summary(fit_2, standardized = TRUE, fit.measures = TRUE, rsquare = TRUE)
semPaths(fit_2,rotation=2)
```


```{r}
#look at intervention 
#cross-lagged full model 
P1 <- P1 %>%
  mutate(Intervention = as.factor(Intervention))

model_3 <- "PLS4compraw3 ~  Intervention + AGE3 + WordSpan
          EOWPVTraw3 ~ Intervention + AGE3 + WordSpan
          EMOtotal3 ~  Intervention + AGE3 + WordSpan"
fit_3 = sem(model_3, data = P1)
summary(fit_3, standardized = TRUE, fit.measures = TRUE, rsquare = TRUE)

```

Regression
```{r}
ggplot(data = P1, aes(x=EMOtotal3)) + geom_histogram()

model_a <- lm(EMOtotal3 ~ AGE3, data = P1)
summary(model_a)
model_b <- lm(EMOtotal3 ~ AGE3 + Gender1 + NVIQSS + WordSpan, data = P1)
summary(model_b)

model_c <- lm(EMOtotal3 ~ AGE3 +  NVIQSS + WordSpan + Intervention, data = P1)
summary(model_c)
```

