---
title: "Graphs"
author: "Shengqi(Iris) Zhong"
date: "4/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(ggthemes)
```

## Have a look at the dataset
```{r import dataset}
library(readxl)
p2 <- read_excel("NIHP2LanguageReadingSDS300.xlsx") %>%
  rename(IQ = `NVIQ SS`) %>%
  mutate(Intervention = as.factor(Intervention))
head(p2)
```

## Graphs
### Gender
```{r gender plot}
gender_plot <- ggplot(p2,aes(x = Gender)) +
  geom_histogram(stat = "count")
gender_plot
```

### Ethnicity
```{r ethnicity plot}
ethnicity_plot <- ggplot(p2,aes(x = Ethnicity)) +
  geom_histogram(stat = "count")
ethnicity_plot
```

### IQ
```{r IQ plot}
iq_plot <- ggplot(p2,aes(x = IQ)) +
  geom_histogram(breaks = seq(50, 160, by = 5)) +
  geom_vline(xintercept = mean(p2$IQ, na.rm = T),
             color = "coral", linetype = "dashed", size = 1) +
  labs(title = "IQ Distribution",
       caption = "The dotted line represents mean IQ.") +
  theme_economist_white()
iq_plot
```

```{r IQ ~ ethnicity plot}
ggplot(p2,aes(x = IQ, fill = Ethnicity, color = Ethnicity)) +
  geom_histogram(breaks = seq(50, 160, by = 5),
                 aes(y = ..density..),
                 position = "identity",
                 alpha = 0.5) +
  geom_vline(xintercept = mean((p2 %>% filter(Ethnicity == "BLACK"))$IQ),
             color = "red", linetype = "dashed", size = 1) +
  geom_vline(xintercept = mean((p2 %>% filter(Ethnicity == "WHITE"))$IQ),
             color = "blue", linetype = "dashed", size = 1)

```

### Verbal rote memory subtest (Wspan)

```{r wspan plot}
wspan_plot <- ggplot(p2,aes(x = Wspan)) +
  geom_histogram(stat = "count") +
  geom_vline(xintercept = mean(p2$Wspan, na.rm = T),
             color = "coral", linetype = "dashed", size = 1) +
  labs(title = "Verbal Memory Distribution",
       caption = "The dotted line represents the mean score") +
  theme_economist_white()
wspan_plot
```

#### not useful

```{r wspan ~ ethnicity plot}
ggplot(p2,aes(x = Wspan, fill = Ethnicity, color = Ethnicity)) +
  geom_histogram(position = "identity") +
  geom_vline(xintercept = mean((p2 %>% filter(Ethnicity == "BLACK"))$Wspan, 
                               na.rm = T),
             color = "red", linetype = "dashed", size = 1) +
  geom_vline(xintercept = mean((p2 %>% filter(Ethnicity == "WHITE"))$Wspan),
             color = "blue", linetype = "dashed", size = 1)
```


### DELV score

```{r}
delv_data <- p2 %>%
  select(Intervention, DELVSTrisk1, DELVSTrisk3) %>%
  rename(Wave_1 = DELVSTrisk1, Wave_3 = DELVSTrisk3) %>%
  pivot_longer(cols = c("Wave_1", "Wave_3"), names_to = "phase", values_to = "score") %>%
  mutate(phase = as.factor(phase))

ggplot(delv_data, aes(x = score, fill = phase, color = phase)) +
  geom_histogram(position = "identity", breaks = seq(0, 12, by = 1.5),
                 aes(y = ..density..),
                 alpha = 0.5)+
  geom_vline(xintercept = mean((delv_data %>% filter(phase == "Wave_1"))$score, na.rm = T),
             color = "red", linetype = "dashed", size = 1) +
  geom_vline(xintercept = mean((delv_data %>% filter(phase == "Wave_3"))$score, na.rm = T),
             color = "blue", linetype = "dashed", size = 1) +
  labs(title = "DELV Screener Risk Test Distribution",
       subtitle = "Colored by wave",
       caption = "The dotted line represents mean scores at the two waves.") +
  theme_economist_white()
```

```{r DELV diff}
delv_data_diff <- p2 %>%
  select(Gender, Intervention, Ethnicity, DELVSTrisk1, DELVSTrisk3) %>%
  mutate(delv_diff = DELVSTrisk1 - DELVSTrisk3,
         Intervention = as.factor(Intervention))

ggplot(delv_data_diff, aes(x = delv_diff)) +
  geom_histogram(breaks = seq(-5, 12, by = 1),
                 aes(y = ..density..)) +
  facet_wrap(~Intervention) +
  coord_flip() +
  geom_vline(xintercept = 0,
             col = "coral", size = 1, linetype = "dashed")
  

```

### Expressive score
```{r expressive}
expressive_data <- p2 %>%
  select(Intervention, Wave_1 = EOWPVTESS1, Wave_3 = EOWPVTESS3) %>%
  pivot_longer(cols = c("Wave_1", "Wave_3"), names_to = "phase", values_to = "score") %>%
  mutate(phase = as.factor(phase))

ggplot(expressive_data, aes(x = score, fill = phase, color = phase)) +
  geom_histogram(position = "identity",
                 aes(y = ..density..),
                 alpha = 0.5)+
  geom_vline(xintercept = mean((expressive_data %>% filter(phase == "Wave_1"))$score, 
                               na.rm = T),
             color = "red", linetype = "dashed", size = 1) +
  geom_vline(xintercept = mean((expressive_data %>% filter(phase == "Wave_3"))$score, na.rm = T),
             color = "blue", linetype = "dashed", size = 1) +
  labs(title = "Expressive One Word Picture Vocabulary \nTest Distribution",
       subtitle = "Colored by wave",
       caption = "The dotted line represents mean scores at the two waves.") +
  theme_economist_white()
```

```{r expressive diff}
expressive_data_diff <- p2 %>%
  select(Gender, Intervention, Ethnicity, EOWPVTESS1, EOWPVTESS3) %>%
  mutate(expressive_diff = EOWPVTESS3 - EOWPVTESS1)

ggplot(expressive_data_diff, aes(x = expressive_diff)) +
  geom_histogram(aes(y = ..density..)) +
  facet_wrap(~Intervention) +
  coord_flip() +
  geom_vline(xintercept = 0,
             col = "coral", size = 1, linetype = "dashed")
  

```

### Phonological Awareness

```{r pa}
pa_data <- p2 %>%
  select(Intervention, Wave_1 = TOPLPASS1, Wave_3 = TOPLPASS3) %>%
  pivot_longer(cols = c("Wave_1", "Wave_3"), names_to = "phase", values_to = "score") %>%
  mutate(phase = as.factor(phase))

ggplot(expressive_data, aes(x = score, fill = phase, color = phase)) +
  geom_histogram(position = "identity",
                 aes(y = ..density..),
                 alpha = 0.5)+
  geom_vline(xintercept = mean((pa_data %>% filter(phase == "Wave_1"))$score, 
                               na.rm = T),
             color = "red", linetype = "dashed", size = 1) +
  geom_vline(xintercept = mean((pa_data %>% filter(phase == "Wave_3"))$score, na.rm = T),
             color = "blue", linetype = "dashed", size = 1) +
  labs(title = "TOPEL Phonological Awareness Test Distribution",
       subtitle = "Colored by wave",
       caption = "The dotted line represents mean scores at the two waves.") +
  theme_economist_white()
```

```{r pa diff}
pa_data_diff <- p2 %>%
  select(Intervention, TOPLPASS1, TOPLPASS3) %>%
  mutate(pa_diff = TOPLPASS3 - TOPLPASS1,
         Intervention = as.factor(Intervention))

ggplot(pa_data_diff, aes(x = pa_diff)) +
  geom_histogram(aes(y = ..density..)) +
  facet_wrap(~Intervention) +
  coord_flip() +
  geom_vline(xintercept = 0,
             col = "coral", size = 1, linetype = "dashed")

ggplot(pa_data_diff, aes(x = pa_diff, fill = Intervention, color = Intervention)) +
  geom_histogram(position = "identity",
                 aes(y = ..density..),
                 alpha = 0.5)+
  geom_vline(xintercept = mean((pa_data_diff %>% filter(Intervention == "0"))$pa_diff, na.rm = T),
             color = "red", linetype = "dashed", size = 1) +
  geom_vline(xintercept = mean((pa_data_diff %>% filter(Intervention == "1"))$pa_diff, na.rm = T),
             color = "blue", linetype = "dashed", size = 1)
  

```

### Woodcock Johnson III Letter-Word test

```{r letter-word}
ggplot(p2, aes(x = WJ3LWSS5, fill = Intervention, color = Intervention)) +
  geom_histogram(aes(y = ..density..),
                 position = "identity",
                 alpha = 0.5)+
  geom_vline(xintercept = mean((p2 %>% filter(Intervention == "0"))$WJ3LWSS5, na.rm = T),
             color = "red", linetype = "dashed", size = 1) +
  geom_vline(xintercept = mean((p2 %>% filter(Intervention == "1"))$WJ3LWSS5, na.rm = T),
             color = "blue", linetype = "dashed", size = 1) +
  labs(title = "Woodcock Johnson III Letter-Word \nIdentification Test Distribution",
       subtitle = "Colored by Intervention / No Intervention",
       x = "score",
       caption = "The dotted line represents mean scores w/ or w/o intervention.") +
  theme_economist_white()
```

```{r letter-word~ethnicity}
ggplot(p2, aes(x = WJ3LWSS5, fill = Ethnicity, color = Ethnicity)) +
  geom_histogram(aes(y = ..density..),
                 position = "identity",
                 alpha = 0.5)+
  geom_vline(xintercept = mean((p2 %>% filter(Ethnicity == "BLACK"))$WJ3LWSS5, na.rm = T),
             color = "red", linetype = "dashed", size = 1) +
  geom_vline(xintercept = mean((p2 %>% filter(Ethnicity == "WHITE"))$WJ3LWSS5, na.rm = T),
             color = "blue", linetype = "dashed", size = 1) +
  labs(title = "Woodcock Johnson III Letter-Word \nIdentification Test Distribution",
       subtitle = "Colored by Ethnicity",
       x = "score",
       caption = "The dotted line represents mean scores for black/white children.") +
  theme_economist_white()
```

### WJIII Passage Comprehension
```{r passage comprehension}
ggplot(p2, aes(x = WJ3PComSS5, fill = Intervention, color = Intervention)) +
  geom_histogram(aes(y = ..density..),
                 position = "identity",
                 alpha = 0.5)+
  geom_vline(xintercept = mean((p2 %>% filter(Intervention == "0"))$WJ3PComSS5, na.rm = T),
             color = "red", linetype = "dashed", size = 1) +
  geom_vline(xintercept = mean((p2 %>% filter(Intervention == "1"))$WJ3PComSS5, na.rm = T),
             color = "blue", linetype = "dashed", size = 1) +
  labs(title = "WJIII Passage Comprehesion Test Distribution",
       subtitle = "Colored by Intervention / No Intervention",
       x = "score",
       caption = "The dotted line represents mean scores w/ or w/o intervention.") +
  theme_economist_white()
```

```{r comprehension~ethnicity}
ggplot(p2, aes(x = WJ3PComSS5, fill = Ethnicity, color = Ethnicity)) +
  geom_histogram(aes(y = ..density..),
                 position = "identity",
                 alpha = 0.5)+
  geom_vline(xintercept = mean((p2 %>% filter(Ethnicity == "BLACK"))$WJ3PComSS5, na.rm = T),
             color = "red", linetype = "dashed", size = 1) +
  geom_vline(xintercept = mean((p2 %>% filter(Ethnicity == "WHITE"))$WJ3PComSS5, na.rm = T),
             color = "blue", linetype = "dashed", size = 1) +
labs(title = "WJIII Passage Comprehesion Test Distribution",
       subtitle = "Colored by Ethnicity",
       x = "score",
       caption = "The dotted line represents mean scores for black/white children.") +
  theme_economist_white()
```


## repeated ANOVA trial
```{r}
anova_data <- p2 %>%
  select(Intervention, wave_1 = DELVSTrisk1, wave_3 = DELVSTrisk3) %>%
  mutate(diff_DELV = wave_3 - wave_1)

m1<-lm(diff_DELV~Intervention, data = anova_data)
summary(aov(m1))
```

